---
title: 'Mineria de dades: PRA2 - Modelatge per a un joc de dades'
author: "Autor: Nom de l'estudiant"
date: "Maig 2021"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
    includes:
      in_header: 05.584-PEC-header.html
  word_document: default
  pdf_document:
    highlight: zenburn
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
******
# Introducció
******
## Presentació
Aquesta pràctica cobreix de manera transversal l'assignatura.

Les Pràctiques 1 i 2 de l'assignatura es plantegen d'una forma conjunta de manera que la Pràctica 2 serà continuació de la 1.

L'objectiu global de la **Pràctica 2** és d'extreure coneixements i de comparar les diferents solucions aplicant tot l'après mitjançant els algorismes de clustering, associació i classificació.

## Competències
Les competències que es treballen en aquesta prova són:

* Ús i aplicació de les TIC en l'àmbit acadèmic i professional.
* Capacitat per a innovar i generar noves idees.
* Capacitat per a avaluar solucions tecnològiques i elaborar propostes de projectes tenint en compte els recursos, les alternatives disponibles i les condicions de mercat.
* Conèixer les tecnologies de comunicacions actuals i emergents així com saber-les aplicar convenientment per a dissenyar i desenvolupar solucions basades en sistemes i tecnologies de la informació.
* Aplicació de les tècniques específiques d'enginyeria del programari en les diferents etapes del cicle de vida d'un projecte.
* Capacitat per a aplicar les tècniques específiques de tractament, emmagatzematge i administració de dades.
* Capacitat per a proposar i avaluar diferents alternatives tecnològiques per a resoldre un problema concret.

## Objetius
La correcta assimilació de tots els aspectes treballats durant el semestre.
En aquesta pràctica abordem un cas real de mineria de dades on hem de posar en joc tots els conceptes treballats.
Cal treballar tot el cicle de vida del projecte. Des de l'objectiu del projecte fins a la implementació del coneixement trobat passant per la preparació, neteja de les dades, coneixement de les dades, generació del model, interpretació i avaluació.

## Descripció de la PRA a realitzar
La pràctica consta d'exercicis en els quals l'estudiant aplicarà alguns dels mètodes supervisats i no supervisats apresos durant el semestre.

## Recursos Bàsics
Material docent proporcionat per la UOC. 

## Criteris de valoració

**Exercicis pràctics** 

Per a totes les PRA és necessari documentar en cada apartat de l'exercici pràctic que s'ha fet i com s'ha fet.

## Format i data d'entrega
El format d'entrega és: **usernameestudiante-PRA2** *.Rmd* i el **output generat** en un d'aquests formats html/*doc/docx/odt/pdf*.

Data de lliurament: **16/06/2021**

S'ha de lliurar la PRA en la bústia de lliuraments de l'aula en format comprimit que inclou els fitxers:
- executable
- output
- el dataset seleccionat o en defecte d'això indicar la ruta per a la seva descàrrega en l'executable.

## Nota: Propietat intel·lectual

> Sovint és inevitable, en produir una obra multimèdia, fer ús de recursos creats per terceres persones. És per tant comprensible fer-ho en el marc d'una pràctica dels estudis d'Informàtica, Multimèdia i Telecomunicació de la UOC, sempre que això es documenti clarament i no suposi plagi en la pràctica.

> Per tant, en presentar una pràctica que faci ús de recursos aliens, s'ha de presentar juntament amb ella un document en el que es detallin tots ells, especificant el nom de cada recurs, el seu autor, el lloc on es va obtenir i el seu estatus legal: si l'obra aquesta protegida pel copyright o s'acull a alguna altra llicència d'ús (Creative Commons, llicència GNU, GPL ...).
L'estudiant haurà d'assegurar-se que la llicència no impedeix específicament el seu ús en el marc de la pràctica. En cas de no trobar la informació corresponent haurà d'assumir que l'obra aquesta protegida per copyright.

> Haureu, a més, adjuntar els fitxers originals quan les obres utilitzades siguin digitals, i el seu codi font si correspon.

******
# Enunciat
******
Com a continuació de l'estudi iniciat en la pràctica 1, procedim a **aplicar models analítics** sobre el joc de dades seleccionat i preparat. En aquesta pràctica 2 s'aconsella d'adjuntar els “chunks” de la part de preparació prèvia, exemple (neteja, discretizació, normalització, PCA/*SVD etc.), o en defecte d'això carregar només les dades ja preparades

D'aquesta manera es demana a l'estudiant que completi els següents passos:

1. Aplicar un model **no supervisat** i basat en el concepte de distància, sobre el joc de dades.

2. Aplicar de nou el model anterior, però usant una **mètrica diferent** i comparar els resultats.

3. Raonar si té sentit aplicar al dataset seleccionat, un mètode de **generació de regles d'associació**. En cas afirmatiu, realitzar tal procés i explicar els resultats. En cas contrari, reformula el problema perquè sí que el tingui.

4. Aplicar un model de generació de regles a partir de **arbres de decisió** sense i amb opcions de poda i comparar els resultats.

5. Aplicar una millora amb **tècniques de boosting** i comparar el resultat amb l'anterior.

6. Identificar eventuals **limitacions** del dataset seleccionat i **analitzar els riscos** per al cas d'ús.

7. (Punt comú per a tots els exercicis) -
En tots els punts anteriors es demana a l'estudiant, a més d'aplicar els diferents mètodes, d'analitzar correctament el problema, **detallar de manera exhaustiva** ressaltant el perquè i com s'ha realitzat, incloent elements visuals, explicant els resultats, realitzar les comparatives oportunes amb les seves conclusions.


******
# Criteris d'avaluació
******

* Exercici 1 (25%)
	- Es genera un model no supervisat.
  - S'analitzen, mostren i comenten les mesures de qualitat del model generat.
  - Es comenten les conclusions.

* Exercici 2 (10%)
	- Es genera de nou el model no supervisat anterior, però usant una mètrica de distància diferent.
  - Es mostren i comenten les mesures de qualitat del model generat.
  - Addicionalment es comparen els dos models no supervisats amb mètriques de distància diferents.
  - Es comenten les conclusions.
	
* Exercici 3 (10%)
  - Es representa, analitza i comenta un exemple de regles d'associació aplicat al dataset seleccionat, o en defecte d'això es reformula el problema (mínim de 250 paraules).
  - Es comenten les conclusions.

* Exercici 4 (25%)
  - Es generen regles i es comenten i interpreten les més significatives.
  - Extraiem les regles del model en format text i gràfic.
  - Addicionalment es genera matriu de confusió per a mesurar la capacitat predictiva de l'algorisme.
  - Es comparen i interpreten els resultats sense i amb opcions de poda, explicant els avantatges i inconvenients del model generat respecte a un altre mètode de construcció.
  - S'avalua la taxa d'error en cada nivell d'arbre, l'eficiència en classificació (en les fases de training, validació i test) i la comprensibilitat.
  - Es comenten les conclusions.

* Exercici 5 (10%)
  - S'aplica una millora amb tècnica de boosting.
  - Es detalla, comenta i avalua la qualitat de classificació.
  - Es comparen i comenten els resultats de manera exhaustiva amb l'anterior mètode de construcció.

* Exercici 6 (10%)
  - Identifica quines possibles limitacions tenen les dades que has seleccionat per a obtenir conclusions amb els models (supervisat i no supervisat)
  - S'identifiquen possibles riscos de l'ús del model (mínim 250 paraules).
  
* Consideració general (10%) 
  - Es presenta el codi i és fàcilment reproduïble.
  - Es detalla cada pregunta de manera correcta, mostrant el codi, comentant com s'ha fet i perquè s'ha fet, comparant els resultats i/o indicant altres alternatives al problema indicat.
  - Es mostren les conclusions en cada apartat.
  - S'indiquen eventuals citacions bibliogràfiques, fonts internes/externes i materials de recerca.

******
# Recursos de programació
******
* Incloem en aquest apartat una llista de recursos de programació per a mineria de dades on podreu trobar exemples, idees i inspiració:
  + [Material addicional del llibre: Mineria de dades Models i Algorismes](http://oer.uoc.edu/libromd/)
  + [Espai de recursos UOC per a ciència de dades](http://datascience.recursos.uoc.edu/es/)
  + [Cercador de codi R](https://rseek.org/)
  + [Col·lecció de cheatsheets en R](https://rstudio.com/resources/cheatsheets/)
  

******
# Implementació 
******

## Model no supervistat

## Regles d’associació

## Tècnica de boosting






